---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-docs-tb
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: short-id
      value: $(extensions.short_sha)