---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-docs-tt
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
    - name: short-id
      description: truncated commit id
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
        labels:
          tekton.dev/pipeline: create-d500-docs
        generateName: create-d500-docs-triggered-run-
      spec:
        params:
        - name: application
          value: do500-docs
        - name: git-url
          value: $(tt.params.gitrepositoryurl)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: short-git-revision
          value: $(tt.params.short-id)
        - name: image-registry
          value: image-registry.openshift-image-registry.svc.cluster.local:5000
        - name: image-repository
          value: jtudela-pipelines
        pipelineRef:
          name: create-d500-docs
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: tekton-test-pvc