apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: create-d500-docs
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: https://github.com/jtudelag/enablement-docs.git
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: master
  - name: IMAGE
    type: string
    description: image to be build from the code
    default: "image-registry.openshift-image-registry.svc:5000/jtudela-pipelines/do500-docs:latest"
  tasks:
    
    - name: fetch-repository
      taskRef:
        name: git-clone-v0-19-0
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: shared-workspace
      params:
      - name: url
        value: $(params.git-url)
      - name: deleteExisting
        value: "true"
      - name: revision
        value: $(params.git-revision)
    
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
      - name: source
        workspace: shared-workspace
      runAfter:
      - fetch-repository
      params:
      - name: TLSVERIFY
        value: "false"
      - name: IMAGE
        value: $(params.IMAGE)