apiVersion: v1
kind: Secret
metadata:
  name: github-deployment-push-secret
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: <base64 encoded private-key>